// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOOklktF6qV-9MTz5OQMtHTs-NzBNd-mM',
    appId: '1:846153736225:web:40dd950ba1f8fd3f6a0360',
    messagingSenderId: '846153736225',
    projectId: 'the-wall-cc76e',
    authDomain: 'the-wall-cc76e.firebaseapp.com',
    storageBucket: 'the-wall-cc76e.firebasestorage.app',
    measurementId: 'G-8BCRFWCC3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOocLG9f3e8F09Zm0Qf7HXdDFfAfrBYAY',
    appId: '1:846153736225:android:957fb031d3b2d9da6a0360',
    messagingSenderId: '846153736225',
    projectId: 'the-wall-cc76e',
    storageBucket: 'the-wall-cc76e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Z3v4HHdt7W33l9SNss6-iBtBzDwvoWk',
    appId: '1:846153736225:ios:88e7f08f76eb37076a0360',
    messagingSenderId: '846153736225',
    projectId: 'the-wall-cc76e',
    storageBucket: 'the-wall-cc76e.firebasestorage.app',
    iosBundleId: 'com.example.wall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4Z3v4HHdt7W33l9SNss6-iBtBzDwvoWk',
    appId: '1:846153736225:ios:88e7f08f76eb37076a0360',
    messagingSenderId: '846153736225',
    projectId: 'the-wall-cc76e',
    storageBucket: 'the-wall-cc76e.firebasestorage.app',
    iosBundleId: 'com.example.wall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOOklktF6qV-9MTz5OQMtHTs-NzBNd-mM',
    appId: '1:846153736225:web:aac7db619ebeaf9c6a0360',
    messagingSenderId: '846153736225',
    projectId: 'the-wall-cc76e',
    authDomain: 'the-wall-cc76e.firebaseapp.com',
    storageBucket: 'the-wall-cc76e.firebasestorage.app',
    measurementId: 'G-27P6EEP1GK',
  );
}
